import { useCallback, useEffect, useRef, useState } from "react";
import type { Badge, Category } from "../types";
import type { TopicComparison } from "../lib/compare";
import { fetchNarrative, narrativeEnabled } from "../lib/narrative";

interface Props {
  /** Always-available deterministic read-out; shown until/unless the AI one lands. */
  localNarrative: string;
  zip: string;
  badge: Badge;
  perCategory: Partial<Record<Category, number>>;
  rows: TopicComparison[];
}

type Status = "idle" | "loading" | "done" | "error";

export default function NarrativePanel({
  localNarrative,
  zip,
  badge,
  perCategory,
  rows,
}: Props) {
  const [status, setStatus] = useState<Status>("idle");
  const [text, setText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Re-fetch only when the underlying result actually changes, not on every
  // render — `rows` and `perCategory` are fresh objects each time.
  const signature = `${zip}|${badge.id}|${rows
    .map((r) => `${r.topic.id}:${r.value}`)
    .join(",")}`;

  // Kept in a ref so `load` doesn't need the changing objects as deps.
  const payload = useRef({ zip, badge, perCategory, rows });
  payload.current = { zip, badge, perCategory, rows };

  const load = useCallback((signal?: AbortSignal) => {
    setStatus("loading");
    setError(null);
    fetchNarrative(payload.current, signal)
      .then((t) => {
        if (signal?.aborted) return;
        setText(t);
        setStatus("done");
      })
      .catch((err: unknown) => {
        if (signal?.aborted) return;
        setError(err instanceof Error ? err.message : "Request failed");
        setStatus("error");
      });
  }, []);

  useEffect(() => {
    if (!narrativeEnabled) return;
    const ctrl = new AbortController();
    load(ctrl.signal);
    return () => ctrl.abort();
  }, [signature, load]);

  const showLocal = !narrativeEnabled || status !== "done" || !text;

  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
      <div className="flex items-baseline justify-between gap-2">
        <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400">
          Read-out
        </p>
        {narrativeEnabled && status === "done" && (
          <button
            type="button"
            onClick={() => load()}
            className="text-[10px] font-semibold uppercase tracking-widest text-indigo-500 transition hover:text-indigo-700"
          >
            Regenerate
          </button>
        )}
      </div>

      {showLocal ? (
        <p className="mt-2 text-sm leading-relaxed text-slate-700">
          {localNarrative}
        </p>
      ) : (
        <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-slate-700">
          {text}
        </p>
      )}

      {narrativeEnabled && status === "loading" && (
        <p className="mt-2.5 flex items-center gap-2 text-[11px] font-medium text-indigo-500">
          <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-indigo-500" />
          Writing a fuller read-out…
        </p>
      )}

      {narrativeEnabled && status === "error" && (
        <div className="mt-2.5 flex items-center justify-between gap-2">
          <p className="text-[11px] text-slate-400">
            Extended read-out unavailable{error ? ` — ${error}` : ""}.
          </p>
          <button
            type="button"
            onClick={() => load()}
            className="shrink-0 text-[11px] font-semibold text-indigo-500 transition hover:text-indigo-700"
          >
            Retry
          </button>
        </div>
      )}

      {narrativeEnabled && status === "done" && (
        <p className="mt-2.5 text-[10px] text-slate-400">
          Extended read-out generated by Workers AI · verify figures against the
          issue cards.
        </p>
      )}
    </section>
  );
}
